# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'matplotlibstaticplotterwidget.ui'
#
# Created: Thu Nov  7 11:15:38 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(875, 496)
        self.gridLayout_2 = QtGui.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtGui.QWidget(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtGui.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.matplotlibPlotterWidget = matplotlibPlotterWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.matplotlibPlotterWidget.sizePolicy().hasHeightForWidth())
        self.matplotlibPlotterWidget.setSizePolicy(sizePolicy)
        self.matplotlibPlotterWidget.setObjectName("matplotlibPlotterWidget")
        self.gridLayout_3.addWidget(self.matplotlibPlotterWidget, 0, 1, 1, 1)
        self.widget_2 = QtGui.QWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(200, 0))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plotcontrols = QtGui.QWidget(self.widget_2)
        self.plotcontrols.setObjectName("plotcontrols")
        self.gridLayout = QtGui.QGridLayout(self.plotcontrols)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.classLabel = QtGui.QLabel(self.plotcontrols)
        self.classLabel.setObjectName("classLabel")
        self.gridLayout.addWidget(self.classLabel, 3, 0, 1, 1)
        self.plotTypeComboBox = QtGui.QComboBox(self.plotcontrols)
        self.plotTypeComboBox.setObjectName("plotTypeComboBox")
        self.gridLayout.addWidget(self.plotTypeComboBox, 0, 1, 1, 1)
        self.data2Label = QtGui.QLabel(self.plotcontrols)
        self.data2Label.setObjectName("data2Label")
        self.gridLayout.addWidget(self.data2Label, 2, 0, 1, 1)
        self.classComboBox = QtGui.QComboBox(self.plotcontrols)
        self.classComboBox.setObjectName("classComboBox")
        self.gridLayout.addWidget(self.classComboBox, 3, 1, 1, 1)
        self.plotTypeLabel = QtGui.QLabel(self.plotcontrols)
        self.plotTypeLabel.setObjectName("plotTypeLabel")
        self.gridLayout.addWidget(self.plotTypeLabel, 0, 0, 1, 1)
        self.data1Label = QtGui.QLabel(self.plotcontrols)
        self.data1Label.setObjectName("data1Label")
        self.gridLayout.addWidget(self.data1Label, 1, 0, 1, 1)
        self.data1ComboBox = QtGui.QComboBox(self.plotcontrols)
        self.data1ComboBox.setObjectName("data1ComboBox")
        self.gridLayout.addWidget(self.data1ComboBox, 1, 1, 1, 1)
        self.data2ComboBox = QtGui.QComboBox(self.plotcontrols)
        self.data2ComboBox.setObjectName("data2ComboBox")
        self.gridLayout.addWidget(self.data2ComboBox, 2, 1, 1, 1)
        self.plotButton = QtGui.QPushButton(self.plotcontrols)
        self.plotButton.setObjectName("plotButton")
        self.gridLayout.addWidget(self.plotButton, 5, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 4, 1, 1, 1)
        self.spaceLabel = QtGui.QLabel(self.plotcontrols)
        self.spaceLabel.setText("")
        self.spaceLabel.setObjectName("spaceLabel")
        self.gridLayout.addWidget(self.spaceLabel, 6, 0, 1, 1)
        self.verticalLayout.addWidget(self.plotcontrols)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.groupBox = QtGui.QGroupBox(self.widget_2)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.saveFigDpiLabel = QtGui.QLabel(self.groupBox)
        self.saveFigDpiLabel.setObjectName("saveFigDpiLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.saveFigDpiLabel)
        self.saveFigDpiLineEdit = QtGui.QLineEdit(self.groupBox)
        self.saveFigDpiLineEdit.setObjectName("saveFigDpiLineEdit")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.saveFigDpiLineEdit)
        self.saveFigFilenameLabel = QtGui.QLabel(self.groupBox)
        self.saveFigFilenameLabel.setObjectName("saveFigFilenameLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.saveFigFilenameLabel)
        self.saveFigFilenameLineEdit = QtGui.QLineEdit(self.groupBox)
        self.saveFigFilenameLineEdit.setObjectName("saveFigFilenameLineEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.saveFigFilenameLineEdit)
        self.saveFigButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveFigButton.sizePolicy().hasHeightForWidth())
        self.saveFigButton.setSizePolicy(sizePolicy)
        self.saveFigButton.setObjectName("saveFigButton")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.saveFigButton)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.closeButton = QtGui.QPushButton(self.widget_2)
        self.closeButton.setObjectName("closeButton")
        self.verticalLayout.addWidget(self.closeButton)
        self.gridLayout_3.addWidget(self.widget_2, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.classLabel.setText(QtGui.QApplication.translate("Dialog", "Classification:", None, QtGui.QApplication.UnicodeUTF8))
        self.data2Label.setText(QtGui.QApplication.translate("Dialog", "Data 2:", None, QtGui.QApplication.UnicodeUTF8))
        self.plotTypeLabel.setText(QtGui.QApplication.translate("Dialog", "Plot Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.data1Label.setText(QtGui.QApplication.translate("Dialog", "Data 1:", None, QtGui.QApplication.UnicodeUTF8))
        self.plotButton.setText(QtGui.QApplication.translate("Dialog", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Save Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.saveFigDpiLabel.setText(QtGui.QApplication.translate("Dialog", "DPI:", None, QtGui.QApplication.UnicodeUTF8))
        self.saveFigDpiLineEdit.setText(QtGui.QApplication.translate("Dialog", "300", None, QtGui.QApplication.UnicodeUTF8))
        self.saveFigFilenameLabel.setText(QtGui.QApplication.translate("Dialog", "Filename:", None, QtGui.QApplication.UnicodeUTF8))
        self.saveFigButton.setText(QtGui.QApplication.translate("Dialog", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setText(QtGui.QApplication.translate("Dialog", "Close", None, QtGui.QApplication.UnicodeUTF8))

from .matplotlibplotterwidget import matplotlibPlotterWidget
